
version: '3.8'

services:
  auth-service:
    build: ./microservices/auth-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
    depends_on:
      - redis
    networks:
      - lawhelp-network

  user-service:
    build: ./microservices/user-service
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    networks:
      - lawhelp-network

  chat-service:
    build: ./microservices/chat-service
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - NODE_ENV=development
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
    networks:
      - lawhelp-network

  notification-service:
    build: ./microservices/notification-service
    ports:
      - "3004:3004"
    environment:
      - PORT=3004
      - NODE_ENV=development
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_FROM_EMAIL=${SENDGRID_FROM_EMAIL}
    depends_on:
      - redis
    networks:
      - lawhelp-network

  api-gateway:
    build: ./microservices/api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - AUTH_SERVICE_URL=http://auth-service:3001
      - USER_SERVICE_URL=http://user-service:3002
      - CHAT_SERVICE_URL=http://chat-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
    depends_on:
      - auth-service
      - user-service
      - chat-service
      - notification-service
    networks:
      - lawhelp-network

  frontend:
    build: .
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api-gateway
    networks:
      - lawhelp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - lawhelp-network

networks:
  lawhelp-network:
    driver: bridge

volumes:
  redis-data:
